### ISSUE TITLE
能不能支持自定义

### ISSUE THREAD

**Issue by mua-haha** [pxzxj/VCSLabel#13]
就是自定义 显示的信息，去掉版本号 啥的，我的太长了

**Comment by pxzxj** [comment]
目前是不支持自定义显示的，暂时也没有这块的开发计划，不好意思

**Comment by mua-haha** [comment]
> 目前是不支持自定义显示的，暂时也没有这块的开发计划，不好意思

没事没事，还是感谢老哥，有空我自己整一个可以自定义的，提交上来
