### ISSUE TITLE
IDEA 2022.2.3版本、VCSLable2.4，GIT插件，不能显示提交人提交时间

### ISSUE THREAD

**Issue by mhiStrat** [pxzxj/VCSLabel#14]
插件重新卸载安装，都不可使用
![vcs](https://user-images.githubusercontent.com/18133427/196319126-2bc41bd0-fef7-49da-94d9-0effebb64786.png)
![idea](https://user-images.githubusercontent.com/18133427/196319130-f8804fb1-6c36-4d3e-ade4-3f9d02a0bae1.png)
![code](https://user-images.githubusercontent.com/18133427/196319139-0f236e13-3dbb-49fd-a9bf-0c3a7d8f9ae3.png)

GIT版本
![git](https://user-images.githubusercontent.com/18133427/196319413-c5a9b842-e482-433b-904c-f9db230d99ca.png)

**Comment by pxzxj** [comment]
你是刚换了新版的IDEA嘛，之前老版本的是能正常显示的吗

**Comment by mhiStrat** [comment]
> 你是刚换了新版的IDEA嘛，之前老版本的是能正常显示的吗

对的，新电脑刚安装的IDEA,BA版本是2022.2.3的。

**Comment by mhiStrat** [comment]
> 你是刚换了新版的IDEA嘛，之前老版本的是能正常显示的吗

不知道是哪里问题。我另外一台电脑上，老版本IDEA没问题

**Comment by pxzxj** [comment]
你确认下你不能显示的项目目录下面 `.git` 文件夹还有没有的

**Comment by mhiStrat** [comment]
> 你确认下你不能显示的项目目录下面 `.git` 文件夹还有没有的
有的 
![111](https://user-images.githubusercontent.com/18133427/196321174-fb707f95-7c58-4a5e-a05f-7fd2acfa4edb.png)

**Comment by pxzxj** [comment]
好的 我这两天自己装个新版本的试下

**Comment by mhiStrat** [comment]
> 好的 我这两天自己装个新版本的试下

行的。这个显示不出来，心里慌得一批。哈哈哈

**Comment by pxzxj** [comment]
嗯嗯 习惯了后面有这么一串东西，没有感觉怪怪的

**Comment by pxzxj** [comment]
我装了个2022.2.3的社区版试了下能正常展示的，你要不新建个项目或者从Github拉个项目看行不行 也许是你这个项目的问题

**Comment by mhiStrat** [comment]
> 我装了个2022.2.3的社区版试了下能正常展示的，你要不新建个项目或者从Github拉个项目看行不行 也许是你这个项目的问题

找到问题原因了。打开的目录不对造成的
IDEA打开的目录必须是 .git 文件夹所在的父级目录。
我的现在一个空间下多个项目，打开的是 .git 文件夹爷爷辈的目录，并没有直接打开相应的项目

**Comment by pxzxj** [comment]
是这样子的，因为我需要判断用的是SVN还是Git，判断方法就是从打开的目录找.git文件夹或者.svn文件夹，找不到就到上一级目录找一直到根目录

**Comment by mhiStrat** [comment]
> 是这样子的，因为我需要判断用的是SVN还是Git，判断方法就是从打开的目录找.git文件夹或者.svn文件夹，找不到就到上一级目录找一直到根目录

明白了，3Q
