### ISSUE TITLE
Name duplication

### ISSUE THREAD

**Issue by Stigmund** [pxzxj/VCSLabel#3]
Same issue as reported here: https://github.com/pxzxj/SVNLabel/issues/1
![Clipboarder 2021 10 04-002](https://user-images.githubusercontent.com/89388714/135827498-7e3d1a7f-4df4-4d48-8105-f88acfacfea0.png)

IntelliiJ IDEA 2021.2.1 (Ultimate) Build #IU-212.5080.55

**Comment by pxzxj** [comment]
According to my experience, this problem will only appear when checking out the project from SVN for the first time After reopening IDEA, it will be normal. Please try to restart IDEA. If the problem still exists, i'll try to fix it
