### ISSUE TITLE
关于更新2.1后的问题

### ISSUE THREAD

**Issue by helee9199** [pxzxj/VCSLabel#5]
因为我们公司只用svn ，所以我在idea中屏蔽了disabled了git插件，因为不屏蔽的话，检出的时候默认总是默认git ，
目前不启用git则无法使用该插件。所以现在必须开启git才能正常使用此功能么？
可否去掉这一限制呢？
谢谢~

**Comment by pxzxj** [comment]
你应该不用屏蔽git插件的，捡出的时候不是可以选择是Git还是SVN的吗，你看我下面的图，你想IDEA肯定没那么傻的嘛 要禁用git才能检出SVN项目
![image](https://user-images.githubusercontent.com/28888745/156276466-d6ffa751-9ecb-45dd-862a-5e241ba17193.png)

**Comment by fenglangjunzi** [comment]
更新到2.1之后，svn方式的label直接都没有了，1.6还是有的

**Comment by pxzxj** [comment]
@fenglangjunzi 我这边是正常的 你要不卸载掉重新装下？这次改了名字直接更新可能会有点问题

**Comment by helee9199** [comment]
> 你应该不用屏蔽git插件的，捡出的时候不是可以选择是Git还是SVN的吗，你看我下面的图，你想IDEA肯定没那么傻的嘛 要禁用git才能检出SVN项目 ![image](https://user-images.githubusercontent.com/28888745/156276466-d6ffa751-9ecb-45dd-862a-5e241ba17193.png)
 不 不是这个意思哦。意思是， 如果有git插件开启的话 这里每次都是git的默认选项 需要手动去切换到subversion
因为电脑是m1的mac 不像windows有小乌龟方便使用 所以用idea自带的svn比较多，然后每次都需要在这个介面 介面去点选框选中svn才可以。 所以我屏蔽了git插件，这里就默认是subversion了， 但是屏蔽了git插件则造成了vcslabel不可用

**Comment by pxzxj** [comment]
@helee9199 新版本确实是强依赖git插件的 我是建议你启用，如果你确实不想启用的话可以访问 https://plugins.jetbrains.com/plugin/14018-vcslabel/versions/stable/86303 这个页面下载1.6版本的压缩包然后选择下图这个从磁盘安装 这样就装回老版本了
![image](https://user-images.githubusercontent.com/28888745/156280640-1bb5762d-ef84-4ca5-9270-4267914f73be.png)

**Comment by pxzxj** [comment]
不好意思 我再排查一下 我先把这个版本隐藏了 你要不按照上面我写的方法手动安装下老版本

**Comment by fenglangjunzi** [comment]
> 不好意思 我再排查一下 我先把这个版本隐藏了 你要不按照上面我写的方法手动安装下老版本

卸载重启idea，有了。不确定上次没有出现是不是没有重启的缘故。

**Comment by helee9199** [comment]
> 不好意思 我再排查一下 我先把这个版本隐藏了 你要不按照上面我写的方法手动安装下老版本

最好一起处理一下啦~强迫症 看到就想更新 XD。
做个判断是不是就可以了？

**Comment by pxzxj** [comment]
> > 不好意思 我再排查一下 我先把这个版本隐藏了 你要不按照上面我写的方法手动安装下老版本
> 
> 最好一起处理一下啦~强迫症 看到就想更新 XD。 做个判断是不是就可以了？

@helee9199 说实话兄弟你做开发就离不开Git的，就算公司项目用SVN，但你总会碰到从GitHub克隆些开源项目来学习或者参考的时候，所以我觉得你迟早也需要启用Git插件的，当然实际上我也确实不知道怎么满足你的需求，这个不是做个判断那么简单，就跟你Maven项目添加依赖一样，就是必须的没得选

**Comment by helee9199** [comment]
> > > 不好意思 我再排查一下 我先把这个版本隐藏了 你要不按照上面我写的方法手动安装下老版本
> > 
> > 
> > 最好一起处理一下啦~强迫症 看到就想更新 XD。 做个判断是不是就可以了？
> 
> @helee9199 说实话兄弟你做开发就离不开Git的，就算公司项目用SVN，但你总会碰到从GitHub克隆些开源项目来学习或者参考的时候，所以我觉得你迟早也需要启用Git插件的，当然实际上我也确实不知道怎么满足你的需求，这个不是做个判断那么简单，就跟你Maven项目添加依赖一样，就是必须的没得选

嗯嗯 好的， 那只能这样啦  感谢~
