### ISSUE TITLE
nothing happened in MacOS12.2.1 and idea2021.2.4

### ISSUE THREAD

**Issue by fakebody** [pxzxj/VCSLabel#6]
I have installed this plugin, but nothing happened, does it need some configuration?

my project is a svn based project, and my macos version is 12.2.1, my idea version is 2021.2.1

restarting idea has been tried.

<img width="760" alt="image" src="https://user-images.githubusercontent.com/14190817/158418729-8db144f6-8daf-405a-a087-7b1c539f132a.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/14190817/158418789-46cb00f8-baed-43f6-bb92-66ba6a0aea43.png">

<img width="753" alt="image" src="https://user-images.githubusercontent.com/14190817/158419514-f689029c-984b-4c3f-851d-7d20f0033ac8.png">

<img width="412" alt="image" src="https://user-images.githubusercontent.com/14190817/158419043-b0565c6e-f8de-46a0-9dbf-61df448d42ba.png">

<img width="374" alt="image" src="https://user-images.githubusercontent.com/14190817/158419078-96511bec-2cb1-40ae-bb06-40d4811808d1.png">

**Comment by pxzxj** [comment]
你应该也是国内的开发吧 我们就用中文吧。
我不确定是因为你用的Mac的原因，插件判断有没有用SVN是根据项目根目录下面是否存在.svn的目录，源代码如下，你看看你项目下面有吗
```java
public class SVNRootUtil {

    private final static Logger LOG = Logger.getInstance(SVNRootUtil.class);

    public static final @NonNls String DOT_SVN = ".svn";

    public static boolean isSVNRoot(@NotNull @NonNls String rootDir) {
        try {
            return isSVNRoot(Paths.get(rootDir));
        }
        catch (InvalidPathException e) {
            e.printStackTrace();
            return false;
        }
    }

    public static boolean isSVNRoot(@NotNull Path rootDir) {
        Path dotSvn = rootDir.resolve(DOT_SVN);
        BasicFileAttributes attributes;
        try {
            attributes = Files.readAttributes(dotSvn, BasicFileAttributes.class);
        }
        catch (IOException ignore) {
            return false;
        }
        return attributes.isDirectory();
    }
}
```

**Comment by fakebody** [comment]
了解了，因为我checkout的是个大目录，项目是其中的一个子目录，所以项目的根目录没有.svn文件夹，在那个大目录下才有.svn文件夹

**Comment by pxzxj** [comment]
哦 这样的话是我考虑的不完善，暂时不做调整了，看后面有没有其他问题或者需求再一起发个新版本

**Comment by pxzxj** [comment]
我发了2.4版本，你升级试下

**Comment by fakebody** [comment]
可以了👍
