### ISSUE TITLE
直接安装2.3版本不显示label

### ISSUE THREAD

**Issue by fenglangjunzi** [pxzxj/VCSLabel#7]
直接安装最新的2.3版本，不会出现label。

先通过离线包安装1.6，可以正常显示label；再从1.6升级到2.3，label消失。
继续装1.6离线包，装好提示我重启idea，label又显示了，此时的版本还是1.6。

不知道是我的问题还是插件的问题，idea版本2021.3.2。

**Comment by pxzxj** [comment]
可能你和 #6 原因是一样的，因为新版本添加了Git支持所以需要判断项目是用了SVN还是Git或者都没用，目前的判断方式是项目根目录下面存在.git文件夹就认为是git项目，存在.svn文件夹就认为是svn项目，都不存在就认为都没用，你看看你项目根目录下面有没有

**Comment by fenglangjunzi** [comment]
> 可能你和 #6 原因是一样的，因为新版本添加了Git支持所以需要判断项目是用了SVN还是Git或者都没用，目前的判断方式是项目根目录下面存在.git文件夹就认为是git项目，存在.svn文件夹就认为是svn项目，都不存在就认为都没用，你看看你项目根目录下面有没有

没有.git文件夹，也没有.svn文件夹。我导入的是一个子项目，.svn文件夹在最外层。

**Comment by fenglangjunzi** [comment]
下载了一个项目，根目录下有 .svn、trunk、branches 3个文件夹，我导入的是trunk下的代码，里面没有 .svn文件夹，也没有 .git文件夹

**Comment by pxzxj** [comment]
明白了，这样的话我应该从项目根目录一直向上遍历父目录，看父目录是否存在.svn或者.git，
我再想想这样有没有问题，没问题的话发个新版本

**Comment by fenglangjunzi** [comment]
赞一个 👍

**Comment by pxzxj** [comment]
我发了个2.4版本，你升级试下，没问题的话我就把这个issue关掉了

**Comment by fenglangjunzi** [comment]
从1.6升级到2.4，label没了；
卸载直接安装2.4，还是没有；
装了2.4，离线包覆盖安装1.6，label有了。

老大，貌似还是有问题呢？

**Comment by pxzxj** [comment]
你确定从你的项目目录向上遍历能找到.svn目录？

**Comment by fenglangjunzi** [comment]
往上两层才有 .svn，现在只支持一层吗？搞不好有更多层呢

**Comment by pxzxj** [comment]
不是啊 会一直循环向上遍历的 直到找到.svn或者到了根目录

**Comment by fenglangjunzi** [comment]
我还是继续用1.6吧😭

**Comment by pxzxj** [comment]
好吧，另一个 #6 跟你一样的问题他升级后就可以了，我也不清楚你为啥还不行
