### ISSUE TITLE
仍然不显示Label

### ISSUE THREAD

**Issue by MartinVon1021** [pxzxj/VCSLabel#9]
IDEA: 2021.3.3
Plugin: 2.4
目录结构： Project 中只有子工程和 webroot，子工程中才有 .svn 文件

Project
Project/subprojectA
Project/subprojectA/.svn
Project/subprojectA/src
Project/subprojectB
Project/subprojectB/.svn
Project/subprojectB/src
Project/webroot

**Comment by pxzxj** [comment]
其实我不太明白为啥你这个父项目不提交svn，然后打开的时候又是打开这个父项目，不过无所谓你只要在Project目录下面新建一个空的.svn目录就好了，这样Label应该就能出来了

**Comment by MartinVon1021** [comment]
> 其实我不太明白为啥你这个父项目不提交svn，然后打开的时候又是打开这个父项目，不过无所谓你只要在Project目录下面新建一个空的.svn目录就好了，这样Label应该就能出来了

OK了，公司老系统，没法
